=begin
#Stacks Blockchain API

#Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

The version of the OpenAPI document: v3.0.3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StacksBlockchainApi::RosettaCoinChange
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe StacksBlockchainApi::RosettaCoinChange do
  let(:instance) { StacksBlockchainApi::RosettaCoinChange.new }

  describe 'test an instance of RosettaCoinChange' do
    it 'should create an instance of RosettaCoinChange' do
      expect(instance).to be_instance_of(StacksBlockchainApi::RosettaCoinChange)
    end
  end
  describe 'test attribute "coin_identifier"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "coin_action"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
      # validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["coin_created", "coin_spent"])
      # validator.allowable_values.each do |value|
      #   expect { instance.coin_action = value }.not_to raise_error
      # end
    end
  end

end
