=begin
#Stacks Blockchain API

#Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 

The version of the OpenAPI document: v3.0.3

Generated by: https://openapi-generator.tech
OpenAPI Generator version: 5.4.0

=end

require 'date'
require 'time'

module StacksBlockchainApi
  # The options that will be sent directly to /construction/metadata by the caller.
  class RosettaOptions
    # sender's address 
    attr_accessor :sender_address

    # Type of operation e.g transfer
    attr_accessor :type

    # This value indicates the state of the operations
    attr_accessor :status

    # Recipient's address
    attr_accessor :token_transfer_recipient_address

    # Amount to be transfered.
    attr_accessor :amount

    # Currency symbol e.g STX
    attr_accessor :symbol

    # Number of decimal places
    attr_accessor :decimals

    # Maximum price a user is willing to pay.
    attr_accessor :gas_limit

    # Cost necessary to perform a transaction on the network
    attr_accessor :gas_price

    #  A suggested fee multiplier to indicate that the suggested fee should be scaled. This may be used to set higher fees for urgent transactions or to pay lower fees when there is less urgency.
    attr_accessor :suggested_fee_multiplier

    # Maximum fee user is willing to pay
    attr_accessor :max_fee

    # Fee for this transaction
    attr_accessor :fee

    # Transaction approximative size (used to calculate total fee).
    attr_accessor :size

    # STX token transfer memo.
    attr_accessor :memo

    # Number of cycles when stacking.
    attr_accessor :number_of_cycles

    # Address of the contract to call.
    attr_accessor :contract_address

    # Name of the contract to call.
    attr_accessor :contract_name

    # Set the burnchain (BTC) block for stacking lock to start.
    attr_accessor :burn_block_height

    # Delegator address for when calling `delegate-stacking`.
    attr_accessor :delegate_to

    # The reward address for stacking transaction. It should be a valid Bitcoin address
    attr_accessor :pox_addr

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'sender_address' => :'sender_address',
        :'type' => :'type',
        :'status' => :'status',
        :'token_transfer_recipient_address' => :'token_transfer_recipient_address',
        :'amount' => :'amount',
        :'symbol' => :'symbol',
        :'decimals' => :'decimals',
        :'gas_limit' => :'gas_limit',
        :'gas_price' => :'gas_price',
        :'suggested_fee_multiplier' => :'suggested_fee_multiplier',
        :'max_fee' => :'max_fee',
        :'fee' => :'fee',
        :'size' => :'size',
        :'memo' => :'memo',
        :'number_of_cycles' => :'number_of_cycles',
        :'contract_address' => :'contract_address',
        :'contract_name' => :'contract_name',
        :'burn_block_height' => :'burn_block_height',
        :'delegate_to' => :'delegate_to',
        :'pox_addr' => :'pox_addr'
      }
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'sender_address' => :'String',
        :'type' => :'String',
        :'status' => :'Object',
        :'token_transfer_recipient_address' => :'String',
        :'amount' => :'String',
        :'symbol' => :'String',
        :'decimals' => :'Integer',
        :'gas_limit' => :'Float',
        :'gas_price' => :'Float',
        :'suggested_fee_multiplier' => :'Float',
        :'max_fee' => :'String',
        :'fee' => :'String',
        :'size' => :'Integer',
        :'memo' => :'String',
        :'number_of_cycles' => :'Integer',
        :'contract_address' => :'String',
        :'contract_name' => :'String',
        :'burn_block_height' => :'Integer',
        :'delegate_to' => :'String',
        :'pox_addr' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'status',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StacksBlockchainApi::RosettaOptions` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StacksBlockchainApi::RosettaOptions`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'sender_address')
        self.sender_address = attributes[:'sender_address']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      end

      if attributes.key?(:'token_transfer_recipient_address')
        self.token_transfer_recipient_address = attributes[:'token_transfer_recipient_address']
      end

      if attributes.key?(:'amount')
        self.amount = attributes[:'amount']
      end

      if attributes.key?(:'symbol')
        self.symbol = attributes[:'symbol']
      end

      if attributes.key?(:'decimals')
        self.decimals = attributes[:'decimals']
      end

      if attributes.key?(:'gas_limit')
        self.gas_limit = attributes[:'gas_limit']
      end

      if attributes.key?(:'gas_price')
        self.gas_price = attributes[:'gas_price']
      end

      if attributes.key?(:'suggested_fee_multiplier')
        self.suggested_fee_multiplier = attributes[:'suggested_fee_multiplier']
      end

      if attributes.key?(:'max_fee')
        self.max_fee = attributes[:'max_fee']
      end

      if attributes.key?(:'fee')
        self.fee = attributes[:'fee']
      end

      if attributes.key?(:'size')
        self.size = attributes[:'size']
      end

      if attributes.key?(:'memo')
        self.memo = attributes[:'memo']
      end

      if attributes.key?(:'number_of_cycles')
        self.number_of_cycles = attributes[:'number_of_cycles']
      end

      if attributes.key?(:'contract_address')
        self.contract_address = attributes[:'contract_address']
      end

      if attributes.key?(:'contract_name')
        self.contract_name = attributes[:'contract_name']
      end

      if attributes.key?(:'burn_block_height')
        self.burn_block_height = attributes[:'burn_block_height']
      end

      if attributes.key?(:'delegate_to')
        self.delegate_to = attributes[:'delegate_to']
      end

      if attributes.key?(:'pox_addr')
        self.pox_addr = attributes[:'pox_addr']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          sender_address == o.sender_address &&
          type == o.type &&
          status == o.status &&
          token_transfer_recipient_address == o.token_transfer_recipient_address &&
          amount == o.amount &&
          symbol == o.symbol &&
          decimals == o.decimals &&
          gas_limit == o.gas_limit &&
          gas_price == o.gas_price &&
          suggested_fee_multiplier == o.suggested_fee_multiplier &&
          max_fee == o.max_fee &&
          fee == o.fee &&
          size == o.size &&
          memo == o.memo &&
          number_of_cycles == o.number_of_cycles &&
          contract_address == o.contract_address &&
          contract_name == o.contract_name &&
          burn_block_height == o.burn_block_height &&
          delegate_to == o.delegate_to &&
          pox_addr == o.pox_addr
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [sender_address, type, status, token_transfer_recipient_address, amount, symbol, decimals, gas_limit, gas_price, suggested_fee_multiplier, max_fee, fee, size, memo, number_of_cycles, contract_address, contract_name, burn_block_height, delegate_to, pox_addr].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :Time
        Time.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        # models (e.g. Pet) or oneOf
        klass = StacksBlockchainApi.const_get(type)
        klass.respond_to?(:openapi_one_of) ? klass.build(value) : klass.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
