language: ruby
cache: bundler
rvm:
  - 2.3
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
script:
  - bundle install --path vendor/bundle
  - bundle exec rspec
  - gem build stacks_blockchain_api_client.gemspec
  - gem install ./stacks_blockchain_api_client-1.0.0.gem
