/*
 * Stacks Blockchain API
 * Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 
 *
 * The version of the OpenAPI document: v3.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package so.hiro.stacks_blockchain_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for BurnchainReward
 */
public class BurnchainRewardTest {
    private final BurnchainReward model = new BurnchainReward();

    /**
     * Model tests for BurnchainReward
     */
    @Test
    public void testBurnchainReward() {
        // TODO: test BurnchainReward
    }

    /**
     * Test the property 'canonical'
     */
    @Test
    public void canonicalTest() {
        // TODO: test canonical
    }

    /**
     * Test the property 'burnBlockHash'
     */
    @Test
    public void burnBlockHashTest() {
        // TODO: test burnBlockHash
    }

    /**
     * Test the property 'burnBlockHeight'
     */
    @Test
    public void burnBlockHeightTest() {
        // TODO: test burnBlockHeight
    }

    /**
     * Test the property 'burnAmount'
     */
    @Test
    public void burnAmountTest() {
        // TODO: test burnAmount
    }

    /**
     * Test the property 'rewardRecipient'
     */
    @Test
    public void rewardRecipientTest() {
        // TODO: test rewardRecipient
    }

    /**
     * Test the property 'rewardAmount'
     */
    @Test
    public void rewardAmountTest() {
        // TODO: test rewardAmount
    }

    /**
     * Test the property 'rewardIndex'
     */
    @Test
    public void rewardIndexTest() {
        // TODO: test rewardIndex
    }

}
