/*
 * Stacks Blockchain API
 * Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 
 *
 * The version of the OpenAPI document: v3.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package so.hiro.stacks_blockchain_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for CoreNodePoxResponse
 */
public class CoreNodePoxResponseTest {
    private final CoreNodePoxResponse model = new CoreNodePoxResponse();

    /**
     * Model tests for CoreNodePoxResponse
     */
    @Test
    public void testCoreNodePoxResponse() {
        // TODO: test CoreNodePoxResponse
    }

    /**
     * Test the property 'contractId'
     */
    @Test
    public void contractIdTest() {
        // TODO: test contractId
    }

    /**
     * Test the property 'firstBurnchainBlockHeight'
     */
    @Test
    public void firstBurnchainBlockHeightTest() {
        // TODO: test firstBurnchainBlockHeight
    }

    /**
     * Test the property 'minAmountUstx'
     */
    @Test
    public void minAmountUstxTest() {
        // TODO: test minAmountUstx
    }

    /**
     * Test the property 'registrationWindowLength'
     */
    @Test
    public void registrationWindowLengthTest() {
        // TODO: test registrationWindowLength
    }

    /**
     * Test the property 'rejectionFraction'
     */
    @Test
    public void rejectionFractionTest() {
        // TODO: test rejectionFraction
    }

    /**
     * Test the property 'rewardCycleId'
     */
    @Test
    public void rewardCycleIdTest() {
        // TODO: test rewardCycleId
    }

    /**
     * Test the property 'rewardCycleLength'
     */
    @Test
    public void rewardCycleLengthTest() {
        // TODO: test rewardCycleLength
    }

    /**
     * Test the property 'rejectionVotesLeftRequired'
     */
    @Test
    public void rejectionVotesLeftRequiredTest() {
        // TODO: test rejectionVotesLeftRequired
    }

    /**
     * Test the property 'totalLiquidSupplyUstx'
     */
    @Test
    public void totalLiquidSupplyUstxTest() {
        // TODO: test totalLiquidSupplyUstx
    }

}
