/*
 * Stacks Blockchain API
 * Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 
 *
 * The version of the OpenAPI document: v3.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package so.hiro.stacks_blockchain_api_client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import so.hiro.stacks_blockchain_api_client.model.SigningPayload;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for RosettaConstructionPayloadResponse
 */
public class RosettaConstructionPayloadResponseTest {
    private final RosettaConstructionPayloadResponse model = new RosettaConstructionPayloadResponse();

    /**
     * Model tests for RosettaConstructionPayloadResponse
     */
    @Test
    public void testRosettaConstructionPayloadResponse() {
        // TODO: test RosettaConstructionPayloadResponse
    }

    /**
     * Test the property 'unsignedTransaction'
     */
    @Test
    public void unsignedTransactionTest() {
        // TODO: test unsignedTransaction
    }

    /**
     * Test the property 'payloads'
     */
    @Test
    public void payloadsTest() {
        // TODO: test payloads
    }

}
