//
// AddressTransactionWithTransfersValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Non Fungible Token asset value. */
public struct AddressTransactionWithTransfersValue: Codable, JSONEncodable, Hashable {

    public var hex: String
    public var repr: String

    public init(hex: String, repr: String) {
        self.hex = hex
        self.repr = repr
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case hex
        case repr
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(hex, forKey: .hex)
        try container.encode(repr, forKey: .repr)
    }
}

