//
// GetStxSupplyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** GET request that returns network target block times */
public struct GetStxSupplyResponse: Codable, JSONEncodable, Hashable {

    /** String quoted decimal number of the percentage of STX that have unlocked */
    public var unlockedPercent: String
    /** String quoted decimal number of the total possible number of STX */
    public var totalStx: String
    /** String quoted decimal number of the STX that have been mined or unlocked */
    public var unlockedStx: String
    /** The block height at which this information was queried */
    public var blockHeight: Int

    public init(unlockedPercent: String, totalStx: String, unlockedStx: String, blockHeight: Int) {
        self.unlockedPercent = unlockedPercent
        self.totalStx = totalStx
        self.unlockedStx = unlockedStx
        self.blockHeight = blockHeight
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unlockedPercent = "unlocked_percent"
        case totalStx = "total_stx"
        case unlockedStx = "unlocked_stx"
        case blockHeight = "block_height"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(unlockedPercent, forKey: .unlockedPercent)
        try container.encode(totalStx, forKey: .totalStx)
        try container.encode(unlockedStx, forKey: .unlockedStx)
        try container.encode(blockHeight, forKey: .blockHeight)
    }
}

