//
// RosettaOperationStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** OperationStatus is utilized to indicate which Operation status are considered successful. */
public struct RosettaOperationStatus: Codable, JSONEncodable, Hashable {

    /** The status is the network-specific status of the operation. */
    public var status: String
    /** An Operation is considered successful if the Operation.Amount should affect the Operation.Account. Some blockchains (like Bitcoin) only include successful operations in blocks but other blockchains (like Ethereum) include unsuccessful operations that incur a fee. To reconcile the computed balance from the stream of Operations, it is critical to understand which Operation.Status indicate an Operation is successful and should affect an Account. */
    public var successful: Bool

    public init(status: String, successful: Bool) {
        self.status = status
        self.successful = successful
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case successful
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(status, forKey: .status)
        try container.encode(successful, forKey: .successful)
    }
}

