//
// RosettaParentBlockIdentifier.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** The block_identifier uniquely identifies a block in a particular network. */
public struct RosettaParentBlockIdentifier: Codable, JSONEncodable, Hashable {

    /** This is also known as the block height. */
    public var index: Int
    /** Block hash */
    public var hash: String

    public init(index: Int, hash: String) {
        self.index = index
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case index
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(index, forKey: .index)
        try container.encode(hash, forKey: .hash)
    }
}

