//
// RosettaCoin.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** If a blockchain is UTXO-based, all unspent Coins owned by an account_identifier should be returned alongside the balance. It is highly recommended to populate this field so that users of the Rosetta API implementation don&#39;t need to maintain their own indexer to track their UTXOs. */
public struct RosettaCoin: Codable, JSONEncodable, Hashable {

    public var coinIdentifier: RosettaAccountBalanceResponseCoinIdentifier
    public var amount: AnyCodable

    public init(coinIdentifier: RosettaAccountBalanceResponseCoinIdentifier, amount: AnyCodable) {
        self.coinIdentifier = coinIdentifier
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case coinIdentifier = "coin_identifier"
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(coinIdentifier, forKey: .coinIdentifier)
        try container.encode(amount, forKey: .amount)
    }
}

