//
// UnanchoredTransactionListResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** GET request that returns unanchored transactions */
public struct UnanchoredTransactionListResponse: Codable, JSONEncodable, Hashable {

    /** The number of unanchored transactions available */
    public var total: Int
    public var results: [AnyCodable]

    public init(total: Int, results: [AnyCodable]) {
        self.total = total
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(results, forKey: .results)
    }
}

