name: Stacks Blockchain API Client
targets:
  Stacks Blockchain API Client:
    type: framework
    platform: iOS
    deploymentTarget: "9.0"
    sources: [StacksBlockchainAPIClient/Classes]
    info:
      path: ./Info.plist
      version: 1.0.0
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
