/*
 * Stacks Blockchain API
 * Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 
 *
 * The version of the OpenAPI document: v3.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package so.hiro.stacks_blockchain_api_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Reward slot holder on the burnchain
 */
@ApiModel(description = "Reward slot holder on the burnchain")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-14T17:31:43.521-05:00[America/Monterrey]")
public class BurnchainRewardSlotHolder {
  public static final String SERIALIZED_NAME_CANONICAL = "canonical";
  @SerializedName(SERIALIZED_NAME_CANONICAL)
  private Boolean canonical;

  public static final String SERIALIZED_NAME_BURN_BLOCK_HASH = "burn_block_hash";
  @SerializedName(SERIALIZED_NAME_BURN_BLOCK_HASH)
  private String burnBlockHash;

  public static final String SERIALIZED_NAME_BURN_BLOCK_HEIGHT = "burn_block_height";
  @SerializedName(SERIALIZED_NAME_BURN_BLOCK_HEIGHT)
  private Integer burnBlockHeight;

  public static final String SERIALIZED_NAME_ADDRESS = "address";
  @SerializedName(SERIALIZED_NAME_ADDRESS)
  private String address;

  public static final String SERIALIZED_NAME_SLOT_INDEX = "slot_index";
  @SerializedName(SERIALIZED_NAME_SLOT_INDEX)
  private Integer slotIndex;

  public BurnchainRewardSlotHolder() { 
  }

  public BurnchainRewardSlotHolder canonical(Boolean canonical) {
    
    this.canonical = canonical;
    return this;
  }

   /**
   * Set to &#x60;true&#x60; if block corresponds to the canonical burchchain tip
   * @return canonical
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Set to `true` if block corresponds to the canonical burchchain tip")

  public Boolean getCanonical() {
    return canonical;
  }


  public void setCanonical(Boolean canonical) {
    this.canonical = canonical;
  }


  public BurnchainRewardSlotHolder burnBlockHash(String burnBlockHash) {
    
    this.burnBlockHash = burnBlockHash;
    return this;
  }

   /**
   * The hash representing the burnchain block
   * @return burnBlockHash
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The hash representing the burnchain block")

  public String getBurnBlockHash() {
    return burnBlockHash;
  }


  public void setBurnBlockHash(String burnBlockHash) {
    this.burnBlockHash = burnBlockHash;
  }


  public BurnchainRewardSlotHolder burnBlockHeight(Integer burnBlockHeight) {
    
    this.burnBlockHeight = burnBlockHeight;
    return this;
  }

   /**
   * Height of the burnchain block
   * @return burnBlockHeight
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Height of the burnchain block")

  public Integer getBurnBlockHeight() {
    return burnBlockHeight;
  }


  public void setBurnBlockHeight(Integer burnBlockHeight) {
    this.burnBlockHeight = burnBlockHeight;
  }


  public BurnchainRewardSlotHolder address(String address) {
    
    this.address = address;
    return this;
  }

   /**
   * The recipient address that validly received PoX commitments, in the format native to the burnchain (e.g. B58 encoded for Bitcoin)
   * @return address
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The recipient address that validly received PoX commitments, in the format native to the burnchain (e.g. B58 encoded for Bitcoin)")

  public String getAddress() {
    return address;
  }


  public void setAddress(String address) {
    this.address = address;
  }


  public BurnchainRewardSlotHolder slotIndex(Integer slotIndex) {
    
    this.slotIndex = slotIndex;
    return this;
  }

   /**
   * The index position of the reward entry, useful for ordering when there&#39;s more than one slot per burnchain block
   * @return slotIndex
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "The index position of the reward entry, useful for ordering when there's more than one slot per burnchain block")

  public Integer getSlotIndex() {
    return slotIndex;
  }


  public void setSlotIndex(Integer slotIndex) {
    this.slotIndex = slotIndex;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BurnchainRewardSlotHolder burnchainRewardSlotHolder = (BurnchainRewardSlotHolder) o;
    return Objects.equals(this.canonical, burnchainRewardSlotHolder.canonical) &&
        Objects.equals(this.burnBlockHash, burnchainRewardSlotHolder.burnBlockHash) &&
        Objects.equals(this.burnBlockHeight, burnchainRewardSlotHolder.burnBlockHeight) &&
        Objects.equals(this.address, burnchainRewardSlotHolder.address) &&
        Objects.equals(this.slotIndex, burnchainRewardSlotHolder.slotIndex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canonical, burnBlockHash, burnBlockHeight, address, slotIndex);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BurnchainRewardSlotHolder {\n");
    sb.append("    canonical: ").append(toIndentedString(canonical)).append("\n");
    sb.append("    burnBlockHash: ").append(toIndentedString(burnBlockHash)).append("\n");
    sb.append("    burnBlockHeight: ").append(toIndentedString(burnBlockHeight)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    slotIndex: ").append(toIndentedString(slotIndex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

