/*
 * Stacks Blockchain API
 * Welcome to the API reference overview for the <a href=\"https://docs.hiro.so/get-started/stacks-blockchain-api\">Stacks Blockchain API</a>.  <a href=\"https://hirosystems.github.io/stacks-blockchain-api/collection.json\" download=\"stacks-api-collection.json\">Download Postman collection</a> 
 *
 * The version of the OpenAPI document: v3.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package so.hiro.stacks_blockchain_api_client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import so.hiro.stacks_blockchain_api_client.model.AnyOfstring;
import so.hiro.stacks_blockchain_api_client.model.RosettaOperation;

/**
 * RosettaConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to /construction/preprocess and /construction/payloads.
 */
@ApiModel(description = "RosettaConstructionParseResponse contains an array of operations that occur in a transaction blob. This should match the array of operations provided to /construction/preprocess and /construction/payloads.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-14T17:31:43.521-05:00[America/Monterrey]")
public class RosettaConstructionParseResponse {
  public static final String SERIALIZED_NAME_OPERATIONS = "operations";
  @SerializedName(SERIALIZED_NAME_OPERATIONS)
  private List<RosettaOperation> operations = new ArrayList<RosettaOperation>();

  public static final String SERIALIZED_NAME_SIGNERS = "signers";
  @SerializedName(SERIALIZED_NAME_SIGNERS)
  private List<AnyOfstring> signers = null;

  public static final String SERIALIZED_NAME_ACCOUNT_IDENTIFIER_SIGNERS = "account_identifier_signers";
  @SerializedName(SERIALIZED_NAME_ACCOUNT_IDENTIFIER_SIGNERS)
  private List<Object> accountIdentifierSigners = null;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public RosettaConstructionParseResponse() { 
  }

  public RosettaConstructionParseResponse operations(List<RosettaOperation> operations) {
    
    this.operations = operations;
    return this;
  }

  public RosettaConstructionParseResponse addOperationsItem(RosettaOperation operationsItem) {
    this.operations.add(operationsItem);
    return this;
  }

   /**
   * Get operations
   * @return operations
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<RosettaOperation> getOperations() {
    return operations;
  }


  public void setOperations(List<RosettaOperation> operations) {
    this.operations = operations;
  }


  public RosettaConstructionParseResponse signers(List<AnyOfstring> signers) {
    
    this.signers = signers;
    return this;
  }

  public RosettaConstructionParseResponse addSignersItem(AnyOfstring signersItem) {
    if (this.signers == null) {
      this.signers = new ArrayList<AnyOfstring>();
    }
    this.signers.add(signersItem);
    return this;
  }

   /**
   * [DEPRECATED by account_identifier_signers in v1.4.4] All signers (addresses) of a particular transaction. If the transaction is unsigned, it should be empty.
   * @return signers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "[DEPRECATED by account_identifier_signers in v1.4.4] All signers (addresses) of a particular transaction. If the transaction is unsigned, it should be empty.")

  public List<AnyOfstring> getSigners() {
    return signers;
  }


  public void setSigners(List<AnyOfstring> signers) {
    this.signers = signers;
  }


  public RosettaConstructionParseResponse accountIdentifierSigners(List<Object> accountIdentifierSigners) {
    
    this.accountIdentifierSigners = accountIdentifierSigners;
    return this;
  }

  public RosettaConstructionParseResponse addAccountIdentifierSignersItem(Object accountIdentifierSignersItem) {
    if (this.accountIdentifierSigners == null) {
      this.accountIdentifierSigners = new ArrayList<Object>();
    }
    this.accountIdentifierSigners.add(accountIdentifierSignersItem);
    return this;
  }

   /**
   * Get accountIdentifierSigners
   * @return accountIdentifierSigners
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getAccountIdentifierSigners() {
    return accountIdentifierSigners;
  }


  public void setAccountIdentifierSigners(List<Object> accountIdentifierSigners) {
    this.accountIdentifierSigners = accountIdentifierSigners;
  }


  public RosettaConstructionParseResponse metadata(Object metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    this.metadata = metadata;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RosettaConstructionParseResponse rosettaConstructionParseResponse = (RosettaConstructionParseResponse) o;
    return Objects.equals(this.operations, rosettaConstructionParseResponse.operations) &&
        Objects.equals(this.signers, rosettaConstructionParseResponse.signers) &&
        Objects.equals(this.accountIdentifierSigners, rosettaConstructionParseResponse.accountIdentifierSigners) &&
        Objects.equals(this.metadata, rosettaConstructionParseResponse.metadata);
  }

  @Override
  public int hashCode() {
    return Objects.hash(operations, signers, accountIdentifierSigners, metadata);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RosettaConstructionParseResponse {\n");
    sb.append("    operations: ").append(toIndentedString(operations)).append("\n");
    sb.append("    signers: ").append(toIndentedString(signers)).append("\n");
    sb.append("    accountIdentifierSigners: ").append(toIndentedString(accountIdentifierSigners)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

